### ISSUE TITLE
Support for JetPack 4.5.1

### ISSUE THREAD

**Issue by Tiryoh** [rt-net/jnm_jupyternotebook#11]
# 現状の問題点

* object_followingサンプルの互換性がない
    * JetPack 4.3はTensorRT 6がインストールされているが、JetPack 4.4以降ではTensorRT 7に更新されている
        * https://github.com/NVIDIA-AI-IOT/jetbot/issues/430#issuecomment-828633641
        * https://github.com/NVIDIA-AI-IOT/jetbot/issues/375#issuecomment-803445929
    * JetPack 4.3を利用したJetBotイメージはPyTorch 1.3.0がインストールされているが、JetPack 4.4以降では1.6.0以降しか利用できない
        * https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-9-0-now-available/72048
            * > The JetPack 4.4 production release (L4T R32.4.3) only supports PyTorch 1.6.0 or newer, due to updates in cuDNN.

# 改善案

- [x] TensorRT 7で使えるTensorRT engine fileの作成 (https://github.com/rt-net/jnm_jupyternotebook/pull/8)
- [ ] ~~PyTorch 1.3.0 to 1.6.0へのmigration~~

# 代替案

# その他

**Comment by Tiryoh** [comment]
[tensorrt_model.py](https://github.com/rt-net/jnm_jupyternotebook/blob/35d3aba87d651206d8ef65d8f14c7d2c05c7121e/jnmouse/tensorrt_model.py)に変更を加えずにPyTorch 1.6でssd_mobilenet_v2_cocoでの推論を実行しようとすると以下のように`refrigerator`になってしまう場合があります。

 ![Screenshot from 2021-11-02 16-27-54](https://user-images.githubusercontent.com/3256629/139805249-f7d87bbf-54a7-44fc-904b-49354f306d88.png)

本来は`keyboard`として認識されるべきです。

（[PyCuda実装版](https://github.com/rt-net/jnm_jupyternotebook/blob/6935eee3d05cf8b776d35835d66df10b75710e7d/notebooks/object_following/live_demo-pucuda.ipynb)での表示）
![Screenshot from 2021-11-02 16-46-56](https://user-images.githubusercontent.com/3256629/139806081-450a8b09-7f38-441e-abea-75358082df31.png)



（[jkjung-avt/tensorrt_demosの`trt_ssd.py`](https://github.com/jkjung-avt/tensorrt_demos/blob/master/trt_ssd.py)での表示）

![Screenshot from 2021-11-02 15-58-47](https://user-images.githubusercontent.com/3256629/139805731-d8cb608b-e22b-4f23-8778-d07db34b1e0f.png)

**Comment by Tiryoh** [comment]
* https://github.com/rt-net/jnm_jupyternotebook/pull/15
    * PyCUDA実装版のjnmouseパッケージ追加
    * object_followingサンプルの更新

上記によりサンプルは一部挙動を変えたものの、動くようになったので本件はcloseとします。

**Comment by cuigaochao** [comment]
AttributeError Traceback (most recent call last)
in 
----> 1 model = ObjectDetector(detector)

/usr/local/lib/python3.6/dist-packages/jnmouse-0.5.0-py3.6.egg/jnmouse/object_detection.py in init(self, engine_path, preprocess_fn)
27 trt.init_libnvinfer_plugins(logger, '')
28 load_plugins()
---> 29 self.trt_model = TRTModel(engine_path)
30 ## If you want to specify input and output, use the following instead of the above.
31 # self.trt_model = TRTModel(engine_path, input_names=[TRT_INPUT_NAME],

/usr/local/lib/python3.6/dist-packages/jnmouse-0.5.0-py3.6.egg/jnmouse/tensorrt_model.py in init(self, engine_path, input_names, output_names, final_shapes)
57 with open(engine_path, 'rb') as f:
58 self.engine = self.runtime.deserialize_cuda_engine(f.read())
---> 59 self.context = self.engine.create_execution_context()
60
61 if input_names is None:
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

Hi! When I use jnmouse_jp451_v3.zip and ssd_mobilenet_v2_coco.engine V4(latest) to do object_following experiment, it always has this error. Could you help me and tell me what should I do? Thank you very much.

**Comment by Tiryoh** [comment]
Hi @cuigaochao, thank you for reaching out.

> ssd_mobilenet_v2_coco.engine V4(latest) 

Do you mean __v0.4__ listed here?
https://jetbot.org/master/examples/object_following.html

As explained below, the v0.4 engine file which NVIDIA publishes is available only for TensorRT 6 (JetPack 4.3).

https://github.com/rt-net/jnm_jupyternotebook/pull/8
https://github.com/NVIDIA-AI-IOT/jetbot/issues/375#issuecomment-803445929

Try using build_engine_from_tensorflow.ipynb to build the engine file for TensorRT 7.

https://github.com/rt-net/jnm_jupyternotebook/blob/master/notebooks/object_following/build_engine_from_tensorflow.ipynb

P.S. 
Please do not start a new discussion on closed issue to keep one topic per one issue. Everyone is welcome to create a new issue!
